// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.productSale.impl;

import com.edpichler.inventory.ProductMovment;
import com.edpichler.productSale.impl.ProductSaleImpl;
import com.edpichler.productSales.SaleStatus;
import java.util.Date;

privileged aspect ProductSaleImpl_Roo_JavaBean {
    
    public Long ProductSaleImpl.getId() {
        return this.id;
    }
    
    public void ProductSaleImpl.setId(Long id) {
        this.id = id;
    }
    
    public ProductMovment ProductSaleImpl.getProductMovment() {
        return this.productMovment;
    }
    
    public void ProductSaleImpl.setProductMovment(ProductMovment productMovment) {
        this.productMovment = productMovment;
    }
    
    public long ProductSaleImpl.getTotal() {
        return this.total;
    }
    
    public void ProductSaleImpl.setTotal(long total) {
        this.total = total;
    }
    
    public Date ProductSaleImpl.getDateSold() {
        return this.dateSold;
    }
    
    public void ProductSaleImpl.setDateSold(Date dateSold) {
        this.dateSold = dateSold;
    }
    
    public SaleStatus ProductSaleImpl.getStatus() {
        return this.status;
    }
    
    public void ProductSaleImpl.setStatus(SaleStatus status) {
        this.status = status;
    }
    
}
