// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.productSales.dto;

import com.edpichler.product.Product;
import com.edpichler.productSales.dto.ProductSellDTO;
import java.util.Date;

privileged aspect ProductSellDTO_Roo_JavaBean {
    
    public Product ProductSellDTO.getProduct() {
        return this.product;
    }
    
    public void ProductSellDTO.setProduct(Product product) {
        this.product = product;
    }
    
    public int ProductSellDTO.getQuantity() {
        return this.quantity;
    }
    
    public void ProductSellDTO.setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    public Date ProductSellDTO.getDateOcurried() {
        return this.dateOcurried;
    }
    
    public void ProductSellDTO.setDateOcurried(Date dateOcurried) {
        this.dateOcurried = dateOcurried;
    }
    
    public Long ProductSellDTO.getValueTotal() {
        return this.valueTotal;
    }
    
    public void ProductSellDTO.setValueTotal(Long valueTotal) {
        this.valueTotal = valueTotal;
    }
    
}
