// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.inventory.impl;

import com.edpichler.inventory.MovmentType;
import com.edpichler.inventory.impl.ProductMovmentImpl;
import com.edpichler.product.Product;
import java.util.Date;

privileged aspect ProductMovmentImpl_Roo_JavaBean {
    
    public Long ProductMovmentImpl.getId() {
        return this.Id;
    }
    
    public void ProductMovmentImpl.setId(Long Id) {
        this.Id = Id;
    }
    
    public Product ProductMovmentImpl.getProduct() {
        return this.product;
    }
    
    public void ProductMovmentImpl.setProduct(Product product) {
        this.product = product;
    }
    
    public MovmentType ProductMovmentImpl.getMovmentType() {
        return this.movmentType;
    }
    
    public void ProductMovmentImpl.setMovmentType(MovmentType movmentType) {
        this.movmentType = movmentType;
    }
    
    public int ProductMovmentImpl.getQuantity() {
        return this.quantity;
    }
    
    public void ProductMovmentImpl.setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    public Date ProductMovmentImpl.getMovmentDate() {
        return this.movmentDate;
    }
    
    public void ProductMovmentImpl.setMovmentDate(Date movmentDate) {
        this.movmentDate = movmentDate;
    }
    
    public String ProductMovmentImpl.getNotes() {
        return this.notes;
    }
    
    public void ProductMovmentImpl.setNotes(String notes) {
        this.notes = notes;
    }
    
}
