// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.serviceSales.dto;

import com.edpichler.service.Service;
import com.edpichler.serviceSales.dto.ServiceSellDTO;
import java.util.Date;

privileged aspect ServiceSellDTO_Roo_JavaBean {
    
    public Service ServiceSellDTO.getService() {
        return this.service;
    }
    
    public void ServiceSellDTO.setService(Service service) {
        this.service = service;
    }
    
    public int ServiceSellDTO.getQuantityHours() {
        return this.quantityHours;
    }
    
    public void ServiceSellDTO.setQuantityHours(int quantityHours) {
        this.quantityHours = quantityHours;
    }
    
    public Date ServiceSellDTO.getDateOcurried() {
        return this.dateOcurried;
    }
    
    public void ServiceSellDTO.setDateOcurried(Date dateOcurried) {
        this.dateOcurried = dateOcurried;
    }
    
    public Long ServiceSellDTO.getValueTotal() {
        return this.valueTotal;
    }
    
    public void ServiceSellDTO.setValueTotal(Long valueTotal) {
        this.valueTotal = valueTotal;
    }
    
}
