// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.person.impl;

import com.edpichler.person.impl.ContactImpl;

privileged aspect ContactImpl_Roo_JavaBean {
    
    public Long ContactImpl.getId() {
        return this.id;
    }
    
    public void ContactImpl.setId(Long id) {
        this.id = id;
    }
    
    public String ContactImpl.getServiceName() {
        return this.serviceName;
    }
    
    public void ContactImpl.setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    
    public String ContactImpl.getContact() {
        return this.contact;
    }
    
    public void ContactImpl.setContact(String contact) {
        this.contact = contact;
    }
    
}
