// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.product.impl;

import com.edpichler.product.impl.ProductImpl;

privileged aspect ProductImpl_Roo_JavaBean {
    
    public Long ProductImpl.getId() {
        return this.id;
    }
    
    public void ProductImpl.setId(Long id) {
        this.id = id;
    }
    
    public String ProductImpl.getName() {
        return this.name;
    }
    
    public void ProductImpl.setName(String name) {
        this.name = name;
    }
    
    public String ProductImpl.getDescription() {
        return this.description;
    }
    
    public void ProductImpl.setDescription(String description) {
        this.description = description;
    }
    
    public String ProductImpl.getBarcode() {
        return this.barcode;
    }
    
    public void ProductImpl.setBarcode(String barcode) {
        this.barcode = barcode;
    }
    
}
