// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.service.impl;

import com.edpichler.service.impl.ServiceImpl;

privileged aspect ServiceImpl_Roo_JavaBean {
    
    public Long ServiceImpl.getId() {
        return this.id;
    }
    
    public void ServiceImpl.setId(Long id) {
        this.id = id;
    }
    
    public String ServiceImpl.getName() {
        return this.name;
    }
    
    public void ServiceImpl.setName(String name) {
        this.name = name;
    }
    
    public String ServiceImpl.getDescription() {
        return this.description;
    }
    
    public void ServiceImpl.setDescription(String description) {
        this.description = description;
    }
    
}
