// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.address.gerado;

import com.edpichler.address.gerado.ViewImpl;

privileged aspect ViewImpl_Roo_EntityUI {
    
    String ViewImpl.sampleField;
    
    public void ViewImpl.sampleMethod() {
        System.out.println("Hello World");
    }
    
}
