// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.serviceSale;

import com.edpichler.service.Service;
import com.edpichler.serviceSale.ServiceSaleImpl;
import com.edpichler.serviceSales.SaleStatus;
import java.util.Date;

privileged aspect ServiceSaleImpl_Roo_JavaBean {
    
    public Long ServiceSaleImpl.getId() {
        return this.id;
    }
    
    public void ServiceSaleImpl.setId(Long id) {
        this.id = id;
    }
    
    public long ServiceSaleImpl.getTotal() {
        return this.total;
    }
    
    public void ServiceSaleImpl.setTotal(long total) {
        this.total = total;
    }
    
    public Date ServiceSaleImpl.getDateSold() {
        return this.dateSold;
    }
    
    public void ServiceSaleImpl.setDateSold(Date dateSold) {
        this.dateSold = dateSold;
    }
    
    public Service ServiceSaleImpl.getService() {
        return this.service;
    }
    
    public void ServiceSaleImpl.setService(Service service) {
        this.service = service;
    }
    
    public int ServiceSaleImpl.getQuantityHours() {
        return this.quantityHours;
    }
    
    public void ServiceSaleImpl.setQuantityHours(int quantityHours) {
        this.quantityHours = quantityHours;
    }
    
    public SaleStatus ServiceSaleImpl.getStatus() {
        return this.status;
    }
    
    public void ServiceSaleImpl.setStatus(SaleStatus status) {
        this.status = status;
    }
    
}
