// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.address.impl;

import com.edpichler.address.City;
import com.edpichler.address.impl.AddressImpl;

privileged aspect AddressImpl_Roo_JavaBean {
    
    public String AddressImpl.getStreet() {
        return this.street;
    }
    
    public void AddressImpl.setStreet(String street) {
        this.street = street;
    }
    
    public String AddressImpl.getComplemento() {
        return this.complemento;
    }
    
    public void AddressImpl.setComplemento(String complemento) {
        this.complemento = complemento;
    }
    
    public String AddressImpl.getPostalCode() {
        return this.postalCode;
    }
    
    public void AddressImpl.setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    public int AddressImpl.getLatitude() {
        return this.latitude;
    }
    
    public void AddressImpl.setLatitude(int latitude) {
        this.latitude = latitude;
    }
    
    public int AddressImpl.getLongitude() {
        return this.longitude;
    }
    
    public void AddressImpl.setLongitude(int longitude) {
        this.longitude = longitude;
    }
    
    public City AddressImpl.getCity() {
        return this.city;
    }
    
    public void AddressImpl.setCity(City city) {
        this.city = city;
    }
    
    public Long AddressImpl.getId() {
        return this.id;
    }
    
    public void AddressImpl.setId(Long id) {
        this.id = id;
    }
    
    public Integer AddressImpl.getVersion() {
        return this.version;
    }
    
    public void AddressImpl.setVersion(Integer version) {
        this.version = version;
    }
    
}
