// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.address.impl;

import com.edpichler.address.CountryState;
import com.edpichler.address.impl.CityImpl;

privileged aspect CityImpl_Roo_JavaBean {
    
    public Long CityImpl.getId() {
        return this.id;
    }
    
    public void CityImpl.setId(Long id) {
        this.id = id;
    }
    
    public String CityImpl.getName() {
        return this.name;
    }
    
    public void CityImpl.setName(String name) {
        this.name = name;
    }
    
    public CountryState CityImpl.getState() {
        return this.state;
    }
    
    public void CityImpl.setState(CountryState state) {
        this.state = state;
    }
    
}
