// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.address.impl;

import com.edpichler.address.CountryState;
import com.edpichler.address.impl.CountryImpl;
import java.util.List;

privileged aspect CountryImpl_Roo_JavaBean {
    
    public Long CountryImpl.getId() {
        return this.id;
    }
    
    public void CountryImpl.setId(Long id) {
        this.id = id;
    }
    
    public String CountryImpl.getName() {
        return this.name;
    }
    
    public void CountryImpl.setName(String name) {
        this.name = name;
    }
    
    public String CountryImpl.getSign() {
        return this.sign;
    }
    
    public void CountryImpl.setSign(String sign) {
        this.sign = sign;
    }
    
    public List<CountryState> CountryImpl.getStates() {
        return this.states;
    }
    
    public void CountryImpl.setStates(List<CountryState> states) {
        this.states = states;
    }
    
}
