// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.edpichler.address.impl;

import com.edpichler.address.Country;
import com.edpichler.address.impl.CountryStateImpl;

privileged aspect CountryStateImpl_Roo_JavaBean {
    
    public Long CountryStateImpl.getId() {
        return this.id;
    }
    
    public void CountryStateImpl.setId(Long id) {
        this.id = id;
    }
    
    public String CountryStateImpl.getSign() {
        return this.sign;
    }
    
    public void CountryStateImpl.setSign(String sign) {
        this.sign = sign;
    }
    
    public String CountryStateImpl.getName() {
        return this.name;
    }
    
    public void CountryStateImpl.setName(String name) {
        this.name = name;
    }
    
    public Country CountryStateImpl.getCountry() {
        return this.country;
    }
    
    public void CountryStateImpl.setCountry(Country country) {
        this.country = country;
    }
    
}
